### ISSUE TITLE
Image resolution setting

### ISSUE THREAD

**Issue by madhunm** [emtrax-ltd/Cura2MoonrakerPlugin#11]
How do i change the resolution of the image that is displayed on the screen? I am using a 3.5" Waveshare display and the image preview is very small.

Thanks!

**Comment by emtrax-ltd** [comment]
1) If you are uploading UFP, then the resolution of thumbnail is fixed (by cura)
2) If you are uploading GCODE with embedded thumbnail, then you can customize the resolution via the settings of the post processing plugin "Create Thumbnail".

![image](https://user-images.githubusercontent.com/60063640/124186503-b0cf1400-dabc-11eb-9904-fe5954b2ab04.png)
