### ISSUE TITLE
Unable to save configured plugin settings

### ISSUE THREAD

**Issue by agrohn** [emtrax-ltd/Cura2MoonrakerPlugin#16]
Unable to save configured plugin settings

Despite typing text in all fields, "Connect Moonraker" window shows only "Close" button, and no "Save Config" button at all. 
In Cura, printing buttons show "Moonraker Plugin", and clicking it displays message to Configure Moonraker in Preferences. 

System information: 

Gentoo Linux
Python 3.8
Cura 4.9.1

**Comment by emtrax-ltd** [comment]
can you provide screenshots?

**Comment by agrohn** [comment]
I was just going over QML and got around the issue by defining minimum height in `resources/qml/MoonrakerConfiguration.qml` as follows: 

```
    Component.onCompleted: {
        actionDialog.minimumWidth = screenScaleFactor * 580;
        actionDialog.minimumHeight = screenScaleFactor * 370;
        actionDialog.maximumWidth = screenScaleFactor * 580;
        actionDialog.maximumHeight = screenScaleFactor * 370;
        minimumHeight = 500;
    }
```
But this was a quick and dirty solution. Somehow the height of buttons is not reflected to window itself.

**Comment by agrohn** [comment]
And for the screenshots, there is the original window without modifications to QML:
![moonraker-issue](https://user-images.githubusercontent.com/2619037/128695492-c99a5b54-f28a-46f5-b83a-036a5cbe1e88.png)

And after explicitly defining minimum height, buttons appeared: 
![moonraker-issue-with-added-height](https://user-images.githubusercontent.com/2619037/128695600-bb3be2fa-9496-4a64-b675-dbebdb8ee082.png)

**Comment by emtrax-ltd** [comment]
i will change height to "410" - does it work for you?

    Component.onCompleted: {
        actionDialog.minimumWidth = screenScaleFactor * 580;
        actionDialog.minimumHeight = screenScaleFactor * 410;
        actionDialog.maximumWidth = screenScaleFactor * 580;
        actionDialog.maximumHeight = screenScaleFactor * 410;
    }

**Comment by agrohn** [comment]
I can confirm that buttons are visible with those settings, thanks!

**Comment by emtrax-ltd** [comment]
fix commited
