### ISSUE TITLE
Small change to my previous PR -- fixes request to power on printer

### ISSUE THREAD

**Issue by truckershitch** [emtrax-ltd/Cura2MoonrakerPlugin#17]
Hi again :)

The old method I wrote once worked, but no longer does.  This new method follows the MR API documentation and (in my opinion) looks cleaner.

I can file a pull request if you wish, or you can just make the change (if you wish).  Either way is fine with me.

Have a look at my last commit for details:

https://github.com/truckershitch/Cura2MoonrakerPlugin/commit/00a5d11c366a27f277dfd3bf436c783265e74e2b

Thanks!

**Comment by emtrax-ltd** [comment]
thx... merged it "manually"
