### ISSUE TITLE
Remember choice in upload dialog for "Start print job"

### ISSUE THREAD

**Issue by bitfabrikken** [emtrax-ltd/Cura2MoonrakerPlugin#19]
Hi, thank you for the great plugin.

I'd like to press as few buttons as possible to upload to Moonraker + start the print (RSI).

Would it be possible to e.g. remember the check selection in the "Start print job" checkbox, or maybe even have an option for changing the blue upload button to "Upload+Print".

Also would be nice to be able to not have the "Print sent to ...." info box pop up after every upload :)

**Comment by emtrax-ltd** [comment]
what about two buttons "Upload" and "Upload & Print " instead of the checkbox?

**Comment by emtrax-ltd** [comment]
update: automatic hiding of "successful" messages (after 30 seconds) will be implemented in the next days.

**Comment by emtrax-ltd** [comment]
FR implemented - checkout newest version
