### ISSUE TITLE
[FR] replacing dots and whitespace in filenames with an underscore or dash

### ISSUE THREAD

**Issue by itCarl** [emtrax-ltd/Cura2MoonrakerPlugin#2]
it would be really nice if the Plug-in could replace dots and whitespaces/spaces with an underscore or a dash instead of cutting/stripping the Filename.

**Examples**:
i have a .stl file with the filename "_test_head_v1.4 (small).stl_"
current filename handling is like "_test_head_v1.[gcode | ufp]_" (file extension doesn't really matter in thsi example)

would i would like is something like this "_test_head_v1_4_small.gcode_" or "_test_head_v1_4-small.gcode_"

*EDIT*
i would really like to inplement it by myself but unfortunately i dont know python that well.

**Comment by emtrax-ltd** [comment]
there is currently no cutting or stripping algorithm for filenames implemented - it takes the suggestion from cura (core) for the filenames to use -> same as for dialog of "save as file". is there any other plugin active in your installation of cura which can enforce this behavior?

no matter... i can imagine a feature for regexp-replace in the filename - so you can 'program' and configure the conversion for your self.

**Comment by itCarl** [comment]
> is there any other plugin active in your installation of cura which can enforce this behavior?

currently i dont have any plug-ins except "yours" (Cura2MoonrakerPlugin)

But Fenne from Ultimaker/Cura#9431 linked me a Plug-in that exactly does what this issue here is about.
in general, i don't like plug ins, i prefer fixed features because then less can go wrong more often

**Comment by emtrax-ltd** [comment]
in the upload-dialog there is only one limitation for filenames ->  maximumLength: 100; 

if you need more, just post it.

**Comment by itCarl** [comment]
i just played around with the Plug-in and stuff and just found something interesting...

> use -> same as for dialog of "save as file".

**Save to File**
![sdfsdfsdf](https://user-images.githubusercontent.com/45098772/112143290-f899f180-8bd7-11eb-84c3-7059fc7dd39c.PNG)

**Upload to Moonraker**
![adasdasdasd](https://user-images.githubusercontent.com/45098772/112143296-f9cb1e80-8bd7-11eb-950f-566ceb456d0e.PNG)


![asdasdasdasdds](https://user-images.githubusercontent.com/45098772/112143294-f9328800-8bd7-11eb-893a-baecc285ffbd.PNG)
![aasdasdasdasd](https://user-images.githubusercontent.com/45098772/112143295-f9cb1e80-8bd7-11eb-84f7-1b6fadf55380.PNG)

**Comment by emtrax-ltd** [comment]
I will check that

**Comment by itCarl** [comment]
I'm trying to figure out were exactly the 'error'
here is what i found so far.

---

if I am not mistaken it's doing the "os.path.splitext(file)" correctly..  (line 94)
...thats weird but its displaying it wrong in the dialog box...

![file_ext](https://user-images.githubusercontent.com/45098772/112149879-becce900-8bdf-11eb-9b64-3c567ca1c2e9.PNG)


https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/blob/97043a926376cabc6882f93832f9e6bc52678b25/MoonrakerPlugin/MoonrakerOutputDevice.py#L92-L107

---
**Just some quick and dirty Debuging** 
![asdasdasdasdsdasd](https://user-images.githubusercontent.com/45098772/112153200-554ed980-8be3-11eb-8d86-beca1e7f4cc1.PNG)
![asdasdasdasd](https://user-images.githubusercontent.com/45098772/112153212-57b13380-8be3-11eb-8b9f-c8cfb4398fc2.PNG)

**Comment by emtrax-ltd** [comment]
thank you for your detailed investigation. i have taken it into account and developed it a little bit more complex but much more flexible. take a look at the new version in the repository.

```
       if fileName:
            fileName = os.path.basename(fileName);
        else:
            fileName = "%s." % Application.getInstance().getPrintInformation().jobName
        
        # Translate filename
        if self._trans_input and self._trans_output:
            transFileName = fileName.translate(fileName.maketrans(self._trans_input, self._trans_output, self._trans_remove if self._trans_remove else ""))
            fileName = transFileName

        self._fileName = fileName  + "." + self._output_format
```


your requirements should be satisfied by the following settings... now available within the configuration wizzard
![image](https://user-images.githubusercontent.com/60063640/112223371-1c862300-8c2a-11eb-816b-e92aa711b14b.png)

**Comment by itCarl** [comment]
That's cool.
Thanks a lot.
