### ISSUE TITLE
error: 204 host requires authorisation

### ISSUE THREAD

**Issue by Kieraneasdale** [emtrax-ltd/Cura2MoonrakerPlugin#20]
Hi there,

Does anyone know or could help with this issue?

![Screenshot 2021-10-06 at 18 58 35](https://user-images.githubusercontent.com/45006607/136258086-3cff38f0-b65f-4571-b872-67a4e663e4da.png)

Get an error when trying to upload to Klipper from cura. I have added the IP address of my PC to the authorized list of addresses in moonraker.config.

UPDATE: #7 does not fix it for me!? Where can i find "~/.moonraker_api_key"  ??

One other question is, for the section in the cura config "name of Moonraker power device". i am assuming this refers to the power device such as a TP link smart plug?

cheers

**Comment by emtrax-ltd** [comment]
http-204 -> /home/pi/.moonraker_api_key  - if it is not there, then take a look -> https://github.com/Arksine/moonraker/blob/master/docs/user_changes.md#april-19th-2021 

power device: it is the device name that was defined in moonraker.conf -> [power device_name]

**Comment by Kieraneasdale** [comment]
I will take a look tonight and report back!

Thanks!

**Comment by emtrax-ltd** [comment]
verify/extend "trusted_clients" in section "authorization" of moonraker.conf
----
[authorization]
 ...
trusted_clients
 192.168.1.30
 192.168.1.0/24

**Comment by Andoramb** [comment]
Hm. Same here:
1. Fetched the api key form the script
2. Checked the trusted_clients (connection OK with Postman)

**Comment by emtrax-ltd** [comment]
really strange! please provide the complete configuration of the plugin (screenshot) and moonraker.

...and are there any hints in the /tmp/moonraker.log or /var/log/nginx/access.log or error.log?

**Comment by Andoramb** [comment]
I have configured user/password to the login in Fluidd;
Got the API key, put everything into the plugin config.

It must be my setup then. Feel free to close this issue :)

**Comment by emtrax-ltd** [comment]
> I have configured user/password to the login in Fluidd; Got the API key, put everything into the plugin config.

the "username / password" in the plugin configuration is for http-basic-auth which can be enforced by the nginx - this option is from older days and has nothing to do with the newer functionality of moonraker. please remove the login credentials (not the api-key) from the plugin and give it a try.
