### ISSUE TITLE
Upload the plugin to the marketplace. 

### ISSUE THREAD

**Issue by nallath** [emtrax-ltd/Cura2MoonrakerPlugin#21]
I think this would be much easier to find if this was uploaded to the marketplace! You can do that via https://contribute.ultimaker.com

Even if you don't want that, you can use it to generate .curapackage files which can be drag & dropped into Cura, making installing it a lot less error prone.

**Comment by psiberfunk** [comment]
I agree, this would be much more useful on the marketplace

**Comment by mvoss96** [comment]
yes please.
I really like using this plugin but because it isn't in the marketplace you have to reinstall the plugin every time you update cura

**Comment by psiberfunk** [comment]
I'd like to, but it's pretty frowned on to take someone's code as your own without permission

**Comment by emtrax-ltd** [comment]
request in progress now

**Comment by psiberfunk** [comment]
Yay !

**Comment by emtrax-ltd** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/60063640/166485599-584d90f1-b8be-445a-93b7-0706de53f459.png">

Done!

**Comment by KoenVanduffel** [comment]
Found it, removed the manually installed version, installed from the market.  It even remembers the settings. Testing to follow.
