### ISSUE TITLE
Bug caused by pop-up window size

### ISSUE THREAD

**Issue by syl2333** [emtrax-ltd/Cura2MoonrakerPlugin#24]
![image](https://user-images.githubusercontent.com/51627311/144562814-58271ee8-a210-44a4-8964-648c0b129a9e.png)
As you can see, the pop-up window is too small for me to see the save option below. Hope you can fix this problem as soon as possible.

**Comment by batista16** [comment]
![image](https://user-images.githubusercontent.com/6854591/148518617-f1732269-88f4-4873-b1c3-a2e3739e65b4.png)

**Comment by bdog1** [comment]
As a temporary suggestion you could change your Screen Resolution and that should allow you to at least be able to click the Save Button. Then change Screen resolution back afterwards.

**Comment by emtrax-ltd** [comment]
i'm currently working on a new version for this dialog

**Comment by keiseven** [comment]
When you have finished filling out the necessary information, click "remove box", press "Tab key" once, and press "space key" once, and the behavior will be the same as if you had clicked save.

**Comment by emtrax-ltd** [comment]
The two dialogs "Connect" and "Upload" have been redesigned. I hope it is correct now.
