### ISSUE TITLE
Feature Request- Change color of displayed .gcode file in the preview

### ISSUE THREAD

**Issue by bdog1** [emtrax-ltd/Cura2MoonrakerPlugin#26]
It would be nice to be able to select the color that the printed item is displayed in . Both in the thumbnail view and the print preview window within Mainsail. Right now the part being printed is displayed in Yellow and I would prefer Red to match my Mainsail Interface "theme"

**Comment by emtrax-ltd** [comment]
There is no way to specify a color for Cura when generating the preview image. In general, it would be better if this feature will be implemented within mainsail -> there you can easily add the css-filter "hue-rotate()" onto the thumbnails and colorize them. The value for the filter could then be set in the ui-theme settings.
