### ISSUE TITLE
Plugin Not Showing In Cura

### ISSUE THREAD

**Issue by teslabol77** [emtrax-ltd/Cura2MoonrakerPlugin#29]
After Installation following the directions, the plugin does not appear under the printer settings
[cura.log](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/files/7967529/cura.log)
.

**Comment by Nordmann1961** [comment]
Have a look here:
https://github.com/emtrax-ltd/Cura2MoonrakerPlugin

The user based installation path is C:\Users\<Your Username>\AppData\Roaming\cura\[version number]\plugins (no admin privileges needed)

I had the same problem, now it works :-)

**Comment by teslabol77** [comment]
I have it running fine on my PC Windows 11 installation. I cannot get it to show on my Mac OS installation following the same folder path listed.

**Comment by psiberfunk** [comment]
This is why it would be better to package this plugin properly in the Ultimaker marketplace for free.. I'm not sure why this hasn't been done.

**Comment by emtrax-ltd** [comment]
solution via #21
