### ISSUE TITLE
Plugin could use a function for "monitor mode"

### ISSUE THREAD

**Issue by psiberfunk** [emtrax-ltd/Cura2MoonrakerPlugin#32]
The octoprint plugin has a way to embed the webcam feed URL from octoprint into Cura.  It would be nice if this plugin did the same for moonraker/Mainsail.

**Comment by psiberfunk** [comment]
Note that this is possible by pulling from the Octoprint API emulation GET:  https://moonraker.readthedocs.io/en/latest/web_api/#get-settings

**Comment by emtrax-ltd** [comment]
next updates and new features in branch [cura5-refactored-monitor](/emtrax-ltd/Cura2MoonrakerPlugin/tree/cura5-refactored-monitor)

**Comment by emtrax-ltd** [comment]
webcam is now supported - control functions will be added in the near future
