### ISSUE TITLE
5.0 support

### ISSUE THREAD

**Issue by devolf92** [emtrax-ltd/Cura2MoonrakerPlugin#33]
I'm really in love with this plugin! Thanks for a great job!
Recently Cura released 5.0 beta but looks like they brake something and plugin stopped to work. While loading Cura says that plugin need to be reinstalled

**Comment by LMS0815** [comment]
You can find addtitonal details at: https://community.ultimaker.com/topic/40288-ultimaker-cura-50-beta/

One major change is that the GUI framework Qt was updated from version 5 to version 6, to support newer operating systems (and fix multiple bugs with the previous version of Qt, which was no longer updated). Unfortunately this means that most of the UI of Cura and its plugins has to be made compatible with this newer version of Qt. Because of that all plugins need to be updated and resubmitted to the Marketplace.

**Comment by emtrax-ltd** [comment]
yo! big change but easy fix. Buuut... i will take this opportunity to do some code refactoring.

**Comment by PhilBaz** [comment]
@emtrax-ltd 

Looking forward to it!!!

Yeah, all plug-ins need to be reworked so currently the plugin 'market place' is totally empty...

**Comment by emtrax-ltd** [comment]
OK... take a look at branch "cura5-refactored" and give it a try! tested it with cura 4.13 and cura 5.0 beta :)

cause of massive refactoring there could be some new bugs now ;)

**Comment by PhilBaz** [comment]
@emtrax-ltd Crash on open....

![Screenshot 2022-04-22 182629](https://user-images.githubusercontent.com/21558241/164838135-ecf6e2f6-41f0-4595-b2ac-fe52ca86864a.jpg)

**Comment by soleshoe** [comment]
plugin not showing in cura 5.0 beta 1 on macOS

I tried adding a "plugins" folder in Cura App then adding plugin in it, but no success.
I tried to add the plugin in .../Application Support/cura/5.0/plugins, but no success either.

**Comment by devolf92** [comment]
![image](https://user-images.githubusercontent.com/15054594/164886826-4c0f53f4-84fa-450f-8e85-5eccadf27fb7.png)
 that what i got with refactored version. but when i restarted app everything worked fine :D

**Comment by emtrax-ltd** [comment]
> ![image](https://user-images.githubusercontent.com/15054594/164886826-4c0f53f4-84fa-450f-8e85-5eccadf27fb7.png) that what i got with refactored version after pressing upload button. but when i restarted app everything worked fine :D

in these cases please attach the cura.log

**Comment by PhilBaz** [comment]
With the updated version Cura now opens and I can get into the moonraker dialogue.....But  1) I cant enter an address, whatever I do it just doesn't hold a value. Double checking, nether dose API or name dialogue hold a value 2) I cant select the 'format' radio button to chose UFP.


![Screenshot 2022-04-23 082053](https://user-images.githubusercontent.com/21558241/164910075-2c3ac93f-61fe-4599-a628-ba90f73e1513.jpg)

**Comment by devolf92** [comment]
[done](https://pastebin.com/tFVLw69r)

**Comment by emtrax-ltd** [comment]
> [done](https://pastebin.com/tFVLw69r)

hmmm.... Not Found (#404)

:(

**Comment by devolf92** [comment]
gdrive my last hope :D i edited my previous post

**Comment by emtrax-ltd** [comment]
> ![image](https://user-images.githubusercontent.com/15054594/164886826-4c0f53f4-84fa-450f-8e85-5eccadf27fb7.png) that what i got with refactored version after pressing upload button. but when i restarted app everything worked fine :D

ok... i saw the log and this error only came up twice. All other times (then later) did the dialog work without problems?

**Comment by PhilBaz** [comment]
All good here after the last round....Seems to be working fine. Cura 5 to MainsailOS UFP with thumb.

Thank you very much!!!

**Comment by emtrax-ltd** [comment]
branch merged...we need more "volunteers" now to find bugs ;)

**Comment by KoenVanduffel** [comment]
Tested the updated plugin in Cura 5.0, Win 10 works like a charm, ufp thumbnail is there. Only the power on of the printer I have not tested yet (configured it and nothing complains at least).

**Comment by emtrax-ltd** [comment]
next updates and new features in branch [cura5-refactored-monitor](/emtrax-ltd/Cura2MoonrakerPlugin/tree/cura5-refactored-monitor)

**Comment by PhilBaz** [comment]
Sweet...ill give er a go in the morning.

**Comment by PhilBaz** [comment]
@emtrax-ltd 

Transfer with thumb is working fine... I see the new cam dialogue. What address does it want? Mine is plugged into the Pi running klipper. Not sure what the address is or how to find it. If you can give me a hint ill test it.

**Comment by KoenVanduffel** [comment]
I haven't tested the Webcam function yet but the url you can find in the settings dialog. Default is URL: /webcam/?action=snapshot

**Comment by PhilBaz** [comment]
using :    /webcam/?action=snapshot    or    /webcam/?action=stream

  The monitor dialogue doesn't show an image.   I got the two URLs above from Mainsail OS. 

But.... Im also pulling the image in Mainsail OS at the moment. So maybe that's the issue?

**Comment by KoenVanduffel** [comment]
I guess you have to prepend the url, or ip

**Comment by PhilBaz** [comment]
Okay......got it!

http://xxx.xxx.x.xxx/webcam/?action=stream

**Comment by emtrax-ltd** [comment]
i will update the logic for webcam url in one of the next versions: absolute (http[s]://..) or relative (/....?..) urls will be supported!

**Comment by emtrax-ltd** [comment]
why "absolute" at this moment: because i dont have any webcams, so i only tested it with an free/private mjpeg-stream somewhere from the internet ;)

**Comment by PhilBaz** [comment]
Yeah, working great!!

Thank you for the excellent toys!!! I would say you should register the plugin with Cura market so more people can use this awesome app. But I imagine its a huge pain in the ass to jump through their hoops.

**Comment by emtrax-ltd** [comment]
The cura marketplace process is still ongoing -> their review step is very slow!

**Comment by emtrax-ltd** [comment]
hopefully that was the last fix for the branch [cura5-refactored-monitor](/emtrax-ltd/Cura2MoonrakerPlugin/tree/cura5-refactored-monitor) - if there are no more bugs, then i will merge this into main

**Comment by emtrax-ltd** [comment]
I think everything is done here
