### ISSUE TITLE
Cant' connect moonraker

### ISSUE THREAD

**Issue by yhira1023** [emtrax-ltd/Cura2MoonrakerPlugin#38]
Hi guys.

I have 2 instance on Klipper.
How do I connect each instance?

<img width="297" alt="image" src="https://user-images.githubusercontent.com/70953099/169512263-b60adf9c-eb3d-48d2-8fa4-d351daa6a271.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/70953099/169512206-6ca2c1bb-5458-44c1-8683-6c170247618f.png">

**Comment by emtrax-ltd** [comment]
use the connection settings of each individual printer - looks like the ui-address is not proxying to moonraker api

**Comment by yhira1023** [comment]
connected successfully via http://10.0.0.17:7126/
Thanks!
