### ISSUE TITLE
Display not large. And port number is required for connect to printer.

### ISSUE THREAD

**Issue by rexstor** [emtrax-ltd/Cura2MoonrakerPlugin#4]
Using CURA 4.8
Fluidd with Klipper

For the display
![image](https://user-images.githubusercontent.com/21095226/112497166-4ffab600-8dc0-11eb-898f-62c542bc9a6c.png)
The button cropped. but i already adjust 
actionDialog.minimumHeight = screenScaleFactor * 320;
and it seams fit nicely.
![image](https://user-images.githubusercontent.com/21095226/112498457-8127b600-8dc1-11eb-9a19-c532424ebeb0.png)

IP address need to put including port number.
If only IP address without port, the file cant be uploaded.

http://192.168.9.112:7125/

Anyway thanks for great plug-in!

**Comment by emtrax-ltd** [comment]
The port must be specified if it deviates from the standard http = 80 or https = 443 - this is practically enforced by the http protocol and headers.

**Comment by emtrax-ltd** [comment]
question: isn't your moonraker behind a nginx?

**Comment by GHswitt** [comment]
@emtrax-ltd I needed to change that to 360, otherwise I couldn't see the Save/remove config buttons.

**Comment by emtrax-ltd** [comment]
@GHswitt fixed in #5
