### ISSUE TITLE
Feature request: Bypass file rename window

### ISSUE THREAD

**Issue by mujeebbasit** [emtrax-ltd/Cura2MoonrakerPlugin#41]
First, thank you for this great plugin.  It has allowed me to completely switch away from Octoprint.  The one thing I never do it change the filename prior to printing.  Therefore, the file rename popup is waste of a click for me.  Could you please add a parameter to auto accept the rename windows?

Thank y ou

**Comment by emtrax-ltd** [comment]
There is a small problem with "Fire and Forget" -> "Upload Only" or "Upload & Print"? I think we need a way to set either of these two options.

**Comment by mujeebbasit** [comment]
Agree, it would be nice to have an option in the setting for that.  I only use "Fire and Forget" because I always need to make sure the printer bed a clear.  The settings options would allow people to change their minds in the future.  Again, thank you for a great plugin; it has been working well for months now.

**Comment by emtrax-ltd** [comment]
Will be available in the next version (1.6.3+).
