### ISSUE TITLE
Feature request: Set and open custom URL

### ISSUE THREAD

**Issue by GerdonAbbink** [emtrax-ltd/Cura2MoonrakerPlugin#45]
Whenever I upload to moonraker it shows the button to 'open in browser'.
This URL is the moonraker address and whenever the 'open in browser' button is clicked it shows the 'Welcome to Moonraker' page instead the page I would love to see (Dashboard of Mainsail).

I would love to see another input field which alters the URL of the 'open in browser' button.

**Comment by emtrax-ltd** [comment]
Will be available in the next version (1.6.3+).
