### ISSUE TITLE
Feature Request: 'Save' button inside dialog

### ISSUE THREAD

**Issue by GerdonAbbink** [emtrax-ltd/Cura2MoonrakerPlugin#46]
Save button on the Connect Moonraker dialog.

Not sure if this was in the plugin at all but there is no button to save the settings you've entered.

You have to press 'Enter' or 'Esc' (which is weird) to save the settings entered.

**Comment by emtrax-ltd** [comment]
Look at the dialog "Machine Settings" - it also has no buttons. I want to get the UI L&F and behavior as close as possible to the original.

**Comment by GerdonAbbink** [comment]
Seems like Cura didn't think this through as well. (IMO)

This FR can be closed
