### ISSUE TITLE
Cancel the changed information when closing or pressing Escape

### ISSUE THREAD

**Issue by GerdonAbbink** [emtrax-ltd/Cura2MoonrakerPlugin#47]
Not sure if this is possible using the close button of the dialog.

I would like to see another dialog asking if you want to discard the changed settings whenever you try to close the dialog or when pressing Escape.

This FR is the result of #46 after figuring out pressing Escape saves the settings.

**Comment by GerdonAbbink** [comment]
With the new information from the comment of @emtrax-ltd I changed this to a bug report.

Whenever the close button is used it does not save the information like in the "Machine Settings" dialog.

**Comment by emtrax-ltd** [comment]
I will check and fix that.
