### ISSUE TITLE
Bug Report: Extra HTTP:// Added on upload.

### ISSUE THREAD

**Issue by MahindraPersaud** [emtrax-ltd/Cura2MoonrakerPlugin#48]
I had to manually remove https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/blob/main/MoonrakerConnection/MoonrakerSettings.py#L60-L62 from the python check and enter only my IP within the URL portion due to the URL upload adding an additional http:// infront of the value set for URL

**Comment by emtrax-ltd** [comment]
How did you recognize that "http://" was added as a prefix when uploading?
