### ISSUE TITLE
[Bug] 'Save Config' outside window boundaries.

### ISSUE THREAD

**Issue by HateFindingNames** [emtrax-ltd/Cura2MoonrakerPlugin#5]
Thanks for this plugin, works like a charm.

BUT: I am unable to reach the 'Save Config' button by mouse. Since the windows is not resizable I have to tab over there (one tab after 'Remove:' box) and hit space to make the settings stick.
There seems to be one more button/box outside the windows boundaries since I can tab one extra time before returning to the URL box.

Running Cura 4.8 on Windows 10 Pro 21H1.

![Screenshot 2021-04-13 130758](https://user-images.githubusercontent.com/52651426/114543346-5c548f00-9c59-11eb-85cc-87b79fbfef31.jpg)

**Comment by emtrax-ltd** [comment]
fixed by setting width=580 and height=370
