### ISSUE TITLE
Request : Connect with start time-lapse feature?

### ISSUE THREAD

**Issue by PhilBaz** [emtrax-ltd/Cura2MoonrakerPlugin#51]
When I start a print from Mainsail I get the option to record a time-lapse. Is it possible to integrate this into the dialogue for uploading? I often use the start print feature, can the same time-lapse on/off toggle be added ?

PS...thanks again! loving the plugin functionality :)

**Comment by emtrax-ltd** [comment]
There are no timelapse related methods or parameters within the Moonraker API - looks like something proprietary between Mainsail and its plugin.

**Comment by PhilBaz** [comment]
@emtrax-ltd  ahh, got it.
