### ISSUE TITLE
Upgraded to 5.1..0 plugin error

### ISSUE THREAD

**Issue by fenixryan** [emtrax-ltd/Cura2MoonrakerPlugin#53]
Could no load, please remove or re-install

Tried from market place and from github

**Comment by emtrax-ltd** [comment]
please attach the cura.log

**Comment by Navyjetfixer** [comment]
Received error connection timed out connecting to Moonraker. 
[cura.log](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/files/9543817/cura.log)

**Comment by emtrax-ltd** [comment]
> Received error connection timed out connecting to Moonraker. [cura.log](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/files/9543817/cura.log)

 HTTP 401: Unauthorized

Looks like missing/incorrect API key or unconfigured host address in [Authorization] -> trusted_clients

**Comment by fenixryan** [comment]
Sorry for delay, sorted now. Multiple versions of cura merging manual install with plugin version causing issue. Un installed everything. Put only one version back and restored backup. Found the duplicate directory and nuked it. All good now.
