### ISSUE TITLE
Timeout-all the time

### ISSUE THREAD

**Issue by andycrane** [emtrax-ltd/Cura2MoonrakerPlugin#56]
Installed plugin in Cura 5.0.0 on a Windows 11 system with plenty of resources. Configured as instructions. Uploaded successfully on the first try, then failed to upload with a timeout error on each subsequent occasion. Uninstalled plugin, rebooted, checked IP allocation, reinstalled, reconfigured and it continues to time out each time. Thanks for the work on this plugin.

**Comment by emtrax-ltd** [comment]
Please attach the cura.log? Is there any power device configured?

**Comment by thghca** [comment]
When printer power turned off upload always timed out. No matter if I filled power device field or not.
Why does the plugin bother checking for power or klipper errors if I just want to upload a file without running job?

**Comment by emtrax-ltd** [comment]
I will rework the upload phase in one of the next releases

**Comment by kted** [comment]
Any progress on this?
