### ISSUE TITLE
UFP

### ISSUE THREAD

**Issue by Roho81** [emtrax-ltd/Cura2MoonrakerPlugin#59]
upload with UFP was working, then when I tried uploading a file, it would pause for a moment and i would get the following error:
"object of type SettingFunction is not JSON serializable"

if i change it to Gcode it works fine. This issue just started happening last night.

**Comment by Liechtenstein1** [comment]
Same issue here! In my case it started with Cura 5.2.1

**Comment by Roho81** [comment]
no mine was working with cura 5.2.1

**Comment by Liechtenstein1** [comment]
If you can solve it, can you share how did you solved it in here?

**Comment by Somed17** [comment]
> It's a bug in Cura and its older/inherited print profiles -> #55

I don't quite understand where to insert the new file UFPWriter.py . I don't see such a script in any of the plugin folders

**Comment by Piezoid** [comment]
Try to save the gcode as .ufp, if it fails, then this is a Cura bug and should be reported on their issue tracker.
A project file and log file (containing the python traceback) would help to diagnose and reproduce this behavior.

> I don't quite understand where to insert the new file UFPWriter.py . I don't see such a script in any of the plugin folders

UFPWriter.py is not a plugin file but a part of Cura python application found it's application folder. Replacing it might help, but it's not recommended to  manually patching the app with a file from a old version.

That fix was merged before the release of 5.2 (Ultimaker/Cura#13473), but something could have been missed with the initial patch or with the changes they added for displaying the setting value on their cloud printing services.

**Comment by Somed17** [comment]
> Try to save the gcode as .ufp, if it fails, then this is a Cura bug and should be reported on their issue tracker. A project file and log file (containing the python traceback) would help to diagnose and reproduce this behavior.



Yes, I couldn't save it as UFP, kura gives a critical error. If you change your personal profile to a standard one, then everything works

**Comment by emtrax-ltd** [comment]
workarounds...
1) recreate your "causing" custom print profiles
2) wait for final release of cura 5.2.1  ;)

**Comment by blendfish** [comment]
Just got the same with 5.2.1 after duplicating the built-in profiles and customising.
