### ISSUE TITLE
explain please: file translation

### ISSUE THREAD

**Issue by jappyjan** [emtrax-ltd/Cura2MoonrakerPlugin#6]
what does it do and how do i set it up?
i dont find any documentation...

**Comment by emtrax-ltd** [comment]
Sorry for the lack of documentation ... will write it very soon.

"Filename Translation" is a feature that allows you to easily manipulate the current job filename (specified by cura) -> find and replace characters or remove some characters. Take a quick look at # 2 ... it's the request for that feature.

**Comment by emtrax-ltd** [comment]
Added explanation of Filename Translation to README.md
