### ISSUE TITLE
Implement camera flip Horizontal and Vertical at Monitor configuration

### ISSUE THREAD

**Issue by emrochabr** [emtrax-ltd/Cura2MoonrakerPlugin#60]
Could you please implement a flip function for camera monitoring feature?

**Comment by emtrax-ltd** [comment]
planned for the next release

**Comment by emtrax-ltd** [comment]
take a look at v1.6.5

**Comment by emrochabr** [comment]
Worked great!! Thanks a lot! Enviado do Email para Windows De: emtrax-ltdEnviado:domingo, 27 de novembro de 2022 21:38Para: emtrax-ltd/Cura2MoonrakerPluginCc:emrochabr; AuthorAssunto: Re: [emtrax-ltd/Cura2MoonrakerPlugin] Implement camera flip Horizontal and Vertical at Monitor configuration (Issue #60) take a look at v1.6.5—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
