### ISSUE TITLE
Thumbnail not showing up 

### ISSUE THREAD

**Issue by larie438** [emtrax-ltd/Cura2MoonrakerPlugin#61]
I did a fresh install of Klipper and Mainsail using KIAUH V5 and followed all the instructions on this page, but no matter what, I can't get the thumbnail to display.

I'm using 
Cura 5.2.1
klipper
v0.10.0-615-g96ea871b
moonraker
v0.7.1-747-g779997c
mainsail
v2.3.1

Can anyone help

**Comment by beamsjr** [comment]
I am also having this issue.
