### ISSUE TITLE
Unknown command:"SDCARD_PRINT_FILE"

### ISSUE THREAD

**Issue by ryangillett1** [emtrax-ltd/Cura2MoonrakerPlugin#63]
Hi

I was unable to connect Moonraker by using URL http://192.168.1.69/, was timing out
I can however connect using http://192.168.1.69:7125

However, when I send a gcode to Klipper, Cura advises 'succesfully completed and job started', but in Klipper i get the error:

Unknown command:"SDCARD_PRINT_FILE"

Originally suspected an unknown character but happens even if filename is 'test6' for example

**Comment by clownwen** [comment]
i meet the same problem, would like to share how you solved the Unknown command?
