### ISSUE TITLE
Object of type is not JSON serializable - Error during upload

### ISSUE THREAD

**Issue by Darkmoner** [emtrax-ltd/Cura2MoonrakerPlugin#65]
Hello,

After clicking Upload to Printer below error apears: [Object of type is not JSON serializable]

![Screenshot 2023-01-08 231557](https://user-images.githubusercontent.com/13020171/211221764-8695ebc1-065f-4a5b-a640-a15f727f00ff.png)

I'm sure it is releated to Cura profile, because after changing to Standard - default , everything works fine.

[bad_profile.zip](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/files/10369634/bad_profile.zip)

Here is my profile what makes crash

**Comment by atroph** [comment]
I've noticed that UFP w/ thumbnail is what is causing the problem for me. 

Standard upload "gcode" format works fine.

**Comment by atroph** [comment]
Looks like a cura bug. 

See here. https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/issues/55#issuecomment-1265732978

**Comment by emtrax-ltd** [comment]
https://github.com/Ultimaker/Cura/issues/13675
