### ISSUE TITLE
[FR]: Add G-Code Preprocessor options

### ISSUE THREAD

**Issue by pedrolamas** [emtrax-ltd/Cura2MoonrakerPlugin#66]
I'm currently working on a [klipper_preprocessor](https://github.com/pedrolamas/klipper-preprocessor) script that currently, performs these tasks:

- Add `SET_PRINT_STATS_INFO` so that Klipper can know what is the exact total layer count, and the current layer number in real-time.
- Run [preprocess_cancellation](https://github.com/kageurufu/preprocess_cancellation) tool to add object cancellation data to the resulting G-Code, enabling Klipper to cancel any specific single object while printing.
- Run [klipper_estimator](https://github.com/Annex-Engineering/klipper_estimator) to add a more accurate time estimation to the resulting G-Code.

While the script is quite easy to use, I wonder if it wouldn't be easier & better to just integrate it by adding a new "Preprocess" tab to the Cura2MoonrakerPlugin settings with these options...

Would this be something you would be interested in?

**Comment by LucaDev** [comment]
I'd love to see the printing time calculated by klipper_estimator to show up in Cura. (Which is not possible in a preprocessor script but a plugin should be able to override the estimate I guess)
