### ISSUE TITLE
JSON error when upload

### ISSUE THREAD

**Issue by darxfame** [emtrax-ltd/Cura2MoonrakerPlugin#68]
Hello. I'm download CURA 5.2.2 and slice my model with tumbnail setting.
When i'm upload it to moonraker i'm had json error.
P.S. in cura 4.12 i'm don't had this error

![Screenshot 2023-02-09 110505](https://user-images.githubusercontent.com/1126563/217752964-3ba09c1b-0105-4768-97e0-6c41d79fccad.jpg)

**Comment by simeonov** [comment]
@darxfame did you manage to fix or found solution to this? I have exact same issue with 5.2.2. It was working fine. I just restart my computer and then stopped working and it shows the error.

**Comment by emtrax-ltd** [comment]
https://github.com/Ultimaker/Cura/issues/13675

**Comment by iqubik** [comment]
same issue

**Comment by Aruta79** [comment]
I found a possible workaround, which may also point at the source of the issue. For me, it shows the error about 95% of the time when trying to upload models with various changes in the profile, but if I change the main material temperature to a custom one directly within the profile, it uploads 100% of the time. I just have to change the temp by 1deg. It seems to be that it's some conflict either with the way the profile is saved, or with another plugin which exposes settings in the profile.

**Comment by fieldOfView** [comment]
This should be fixed in Cura 5.3
