### ISSUE TITLE
Latest Klipper and Moonraker cause HTTP 204 errors on upload

### ISSUE THREAD

**Issue by jeremyfuksa** [emtrax-ltd/Cura2MoonrakerPlugin#7]
About two weeks ago, I updated klipper and moonraker. Now, when I try to upload gcode from Cura to my printer, I receive this error: `There was a network error: 204 Host requires authentication`.

I downloaded and reinstalled Cura2Moonraker, triple checked my config, and all should be OK. Still nothing.

Generating and adding an API key to the config also did not help.

- Klipper version: v0.9.1-518-gd6197964
- Moonraker version: v0.6.0-134-g2db727e

**Comment by emtrax-ltd** [comment]
try using the api-key from "~/.moonraker_api_key" - should work.

**Comment by emtrax-ltd** [comment]
i think it's solved
