### ISSUE TITLE
Manuell install dont show up inside Marketplace

### ISSUE THREAD

**Issue by badplay** [emtrax-ltd/Cura2MoonrakerPlugin#71]
Hi

i installed this plugin and works great but when i look in marketplace it want show up as installed  there. so i install it with marketplace maybe i get auto updates? is this  okay what i does or will this make issues ?

**Comment by emtrax-ltd** [comment]
there is a delay of 2-3 weeks until the latest version from github will be available in the marketplace - approval process needs time. you will get a notification in cura if this update will be available.

**Comment by nallath** [comment]
I'm reviewing it right now, sorry for the delay.
