### ISSUE TITLE
Uploading fails (timeout)

### ISSUE THREAD

**Issue by Nuc1eoN** [emtrax-ltd/Cura2MoonrakerPlugin#82]
Hello I have just installed `Cura2MoonrakerPlugin` and configured my printers IP including port number.

However uploading fails:
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/2538022/4fc51d19-c6b6-43d9-832a-5dd684ac48aa)

Cura log:
```markdown
INFO - [MainThread] MoonrakerConnection.MoonrakerOutputDevice._onUploadFilenameAccepted [254]: Connecting to Moonraker at http://192.168.0.107:7125
/.
DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [369]: request[3e301e85][get][PyQt6.QtCore.QUrl('')][timeout=None][no-data] got an QNetworkReplyError Error transferring  - server replied: Bad Request. The server returned: b'<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n'
```

The mailsail interface is reachable over my web browser. Moonraker also is up and running:
http://192.168.0.107:7125/server/info
```json
{"result": {"klippy_connected": true, "klippy_state": "ready", "components": ["klippy_connection", "application", "jsonrpc", "internal_transport", "websockets", "dbus_manager", "database", "file_manager", "klippy_apis", "secrets", "template", "shell_command", "machine", "data_store", "proc_stats", "job_state", "job_queue", "http_client", "announcements", "webcam", "extensions", "history", "update_manager", "octoprint_compat", "authorization"], "failed_components": [], "registered_directories": ["config", "logs", "gcodes", "config_examples", "docs"], "warnings": [], "websocket_count": 2, "moonraker_version": "v0.8.0-231-gcc5dea7", "missing_klippy_requirements": [], "api_version": [1, 4, 0], "api_version_string": "1.4.0"}}
```
http://192.168.0.107:7125/
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/2538022/35c44dd6-94f2-4faf-8e28-f136e76f28df)

I have also checked firewall but it all seems ok. Only the Cura2MoonrakerPlugin seems to have a problem connecting.

Cura v5.6

EDIT:
I was thinking of chiming in on #81 however my printer is turned ON and the upload still fails.
Here is the http://192.168.0.107:7125/printer/info response:
```json
{"result": {"state": "ready", "state_message": "Printer is ready", "hostname": "asx1", "klipper_path": "/home/printman/klipper", "python_path": "/home/printman/klippy-env/bin/python", "process_id": 520, "user_id": 1000, "group_id": 1000, "log_file": "/home/printman/printer_data/logs/klippy.log", "config_file": "/home/printman/printer_data/config/printer.cfg", "software_version": "v0.12.0-40-g77619e91", "cpu_info": "4 core ARMv7 Processor rev 4 (v7l)"}}
```

**Comment by ThGIGA** [comment]
The same thing is happening to me.  Please help.  !!!

I'm using the OctoPrint plugin at the moment which "does work" (kinda), but it's missing information when I see Mainsail.  

However, I would prefer to use the Moonraker plugin because when i upload the file to the printer because it appears with more information un the web.

**Comment by Nuc1eoN** [comment]
@ThGIGA just for your information, orcaslicer works great with mainsail out of the box, no need for a plugin!

**Comment by emtrax-ltd** [comment]
Are you using the latest version 1.7.2 of the plugin?

**Comment by ThGIGA** [comment]
@emtrax-ltd, yes ,I have downloaded it from the market and from here, Github. And I haven't been able to get it to work.

**Comment by Nuc1eoN** [comment]
@emtrax-ltd I am on v1.7.2 from marketplace, yes.

**Comment by emtrax-ltd** [comment]
Try out this branch: https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/tree/pwrdevfix - in this branch are some changes in the process of connecting and uploading

**Comment by ThGIGA** [comment]
![Sin título](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/84819548/aa284b82-260d-4861-845d-1347542b4b17)
 
 Still not working ... Sad

**Comment by emtrax-ltd** [comment]
> ![Sin título](https://private-user-images.githubusercontent.com/84819548/295078674-aa284b82-260d-4861-845d-1347542b4b17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTYzMDgsIm5iZiI6MTcwNDc5NjAwOCwicGF0aCI6Ii84NDgxOTU0OC8yOTUwNzg2NzQtYWEyODRiODItMjYwZC00ODYxLTg0NWQtMTM0NzU0MmI0YjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwMjY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMmUzMTllYjQzOWVmMTcxNzY0ZTU1YjJlMDA1ZWU5YzE5MTY1NGYwMDBkNTdhN2M1MTI0NjU3ZTM2MDY2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUnXiaxf6CVK_lII1z7rBs2o7G5n0eTzETRtQGs3wqM)
> 
> Still not working ... Sad

I don't know about your Moonraker/Klipper installation, but it looks like the Moonraker API is not reverse-proxyed (Nginx) over port 80. Therefore, it is probably necessary to specifically specify the port of the Moonraker API in the plugin configuration -> http://192.168.0.127:7125

**Comment by ThGIGA** [comment]
@emtrax-ltd 
It seems to be working now with the latest version and setting the IP with the port as shown in the image of the plugin

@Nuc1eoN Try this with the latest version, see if it works for you too. 
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/84819548/de5784fa-393c-4f87-9fac-a7b2de8f3850)
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/84819548/602d0955-59cf-4d2b-b4e4-d416bcd50bb4)
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/84819548/8481cc29-a641-4829-a649-be0a7272b822)

**Comment by Nuc1eoN** [comment]
It does not work here:
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/2538022/7cd6a19b-febe-4843-bdea-b80cffa996c4)

>I don't know about your Moonraker/Klipper installation, but it looks like the Moonraker API is not reverse-proxyed (Nginx) over port 80. Therefore, it is probably necessary to specifically specify the port of the Moonraker API in the plugin configuration -> http://192.168.0.127:7125/

I have the stock mainsail OS setup on raspi pretty much.

**Comment by ThGIGA** [comment]
@Nuc1eoN did u try on this branch: https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/tree/pwrdevfix ?

**Comment by Nuc1eoN** [comment]
Yes that is the branch I've used.

Before I've used that branch, the error message was different (timeout). Now it says 'NetworkError...' like in the screenshot
