### ISSUE TITLE
Odd issues since last update

### ISSUE THREAD

**Issue by therealzoomgod** [emtrax-ltd/Cura2MoonrakerPlugin#86]
Ever since last update the plugin has been acting strange.  It randomly closes before saying if it succeeded or failed.  It shows progress of upload at 100% then just vanishes and gcode does not appear in Mainsail interface.

Clicking upload again usually does nothing, the plugin does not appear but oddly that sometimes causes it to magically complete and show up in Mainsail.  Most times it does nothing without restarting Cura numerous times.  

If I save the gcode to disk in Cura and then go into mainsail interface I can upload the file every time.  I've also tried adding the port for Moonraker since I've read about issues with ngix.  That did nothing either, not even sure if ngix is still used.

I'm running the latest Cura release (5.7).  I thought maybe it had something to do with me adding the printer settings plugin for hardware retraction but I tried uninstalling that and saw no change in behavior.   I'd say on 80% of files it works great the rest are a mystery.

**Comment by emtrax-ltd** [comment]
Try release v1.8.0
