### ISSUE TITLE
UFP Thumbnail not appearing (v1.9.1)

### ISSUE THREAD

**Issue by Codename-11** [emtrax-ltd/Cura2MoonrakerPlugin#92]
After updating to the current latest version - 1.9.1 in Cura 5.7.1, the upload with the path set to root - "/", the thumbnail doesn't appear to be uploading properly. The gcode file uploads successfully, just without a thumbnail... :(

The upload in the screenshot with the thumbnail is from the previous version, all settings/connection config for the plugin remain unchanged other than adding the "/" path for the upload.
![image](https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/assets/10284999/891b6dc8-cb3e-42e4-b6d5-4894e908ce3f)

**Comment by emtrax-ltd** [comment]
try empty path (default at top).... empty is root
